### ISSUE TITLE
Direct Transfer results

### ISSUE THREAD

**Issue by liangbh6** [LcDog/DomainAdaptiveReID#1]
Did you combine the softmax loss and triplet loss to train the model on source data? It seems that the results are higher than using the model only trained with softmax loss. Additionally, what about the testing scores of the model on source data?

**Comment by lsongx** [comment]
yeah, softmax and triplet are combined

on Market1501
```
Mean AP: 78.2%
CMC Scores    allshots      cuhk03  market1501
  top-1          58.4%       81.3%       91.5%
  top-5          74.9%       94.8%       97.0%
  top-10         81.2%       97.1%       98.4%
```

on DukeMTMC
```
Mean AP: 65.2%
CMC Scores    allshots      cuhk03  market1501
  top-1          47.6%       69.0%       80.7%
  top-5          61.8%       84.5%       91.1%
  top-10         68.3%       88.3%       94.2%
```

**Comment by liangbh6** [comment]
Thanks very much. By the way, have you released the code of combined strategy? I have tried that before, but it seems that adding the triplet loss has no effect on the testing scores.

**Comment by lsongx** [comment]
Hi @liangbh6 , I have just uploaded the codes of training on the source dataset. Feel free to ask me if you encount other problems.
