### ISSUE TITLE
Question about Msmt dataset

### ISSUE THREAD

**Issue by justopit** [LcDog/DomainAdaptiveReID#17]
When you take Msmt as target dataset, what's your result at 1 GPU. Compared to 4 GPU, is it very bad?

**Comment by lsongx** [comment]
@justopit We dont have such results. I think the performance will drop about 5 points if training with 1 GPU.

**Comment by justopit** [comment]
> @justopit We dont have such results. I think the performance will drop about 5 points if training with 1 GPU.

Thank you
