### ISSUE TITLE
Data selection of PKU-VehicleID

### ISSUE THREAD

**Issue by yxgeee** [LcDog/DomainAdaptiveReID#25]
Hi,

Thanks for your work!
I wonder how do you sample images for PKU-VehicleID (24,157 images of 2,290 IDs) in your experiments? Could you please share the image list?
Plus, do you have the results for Veri->PKU experiments?

Thanks!

**Comment by lsongx** [comment]
Hi @yxgeee ,

Thanks for your interest in our work. 
I am really sorry that the image list is not available anymore. Maybe you can generate one by yourself and re-run the code. 
We didn't run the Veri->PKU setting. Camera IDs are not provided in PKU, so we cannot evaluate the performance as on person ReID datasets.
