### ISSUE TITLE
ConnectionResetError: [Errno 104] Connection reset by peer

### ISSUE THREAD

**Issue by SWRDFK** [LcDog/DomainAdaptiveReID#3]
Hi, author. Thank you for your excellent work! I have met some problems when I run selftraining.py. I chooce DukeMTMC-reID as the source dataset and Market-1501 as the target dataset. Following is the error after epoch 38 of iteration 6:
Exception in thread Thread-403:
...
ConnectionResetError: [Errno 104] Connection reset by peer
I execute this on  Ubuntu 14.04.5 LTS. It seems that SSL reset the connection. So how to solve the problem and what process can I follow to recurrent the result?

**Comment by lsongx** [comment]
I didn't have this problem before. It seems that this is a bug of PyTorch. Maybe this link [pytorch issues #9127](https://github.com/pytorch/pytorch/issues/9127) is useful to you.

**Comment by SWRDFK** [comment]
Thank you for your reply, author. I upgraded PyTorch to 0.4.0 and the problem was solved.
