### ISSUE TITLE
when I train the model from duke to market, it takes too much time and not finish yet after two days.

### ISSUE THREAD

**Issue by zhuhongyue** [LcDog/DomainAdaptiveReID#4]
My execute command is :
```
CUDA_VISIBLE_DEVICES=0,1 python2 selftraining.py  --src_dataset dukemtmc\
	        --tgt_dataset market1501\
		--resume dukemtmc_trained.pth.tar\
		--data_dir data  \
		--logs_dir log
```
PS: my gpu situation:
```
 Sat Oct 27 13:02:49 2018       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 396.24                 Driver Version: 396.24                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1080    Off  | 00000000:02:00.0  On |                  N/A |
| 56%   68C    P2    59W / 200W |   5510MiB /  8119MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 108...  Off  | 00000000:81:00.0 Off |                  N/A |
| 61%   85C    P2    85W / 250W |   5435MiB / 11178MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0       905      C   python2                                     5003MiB |
|    0      1774      G   /usr/lib/xorg/Xorg                           310MiB |
|    0      4274      G   compiz                                       172MiB |
|    0      4427      G   ...webkit2gtk-3.0/libexec/WebKitWebProcess    13MiB |
|    1       905      C   python2                                     5423MiB |
```

**Comment by lsongx** [comment]
@zhuhongyue I trained on two Titan X, and finished in about 12 hours for 30 iterations. The `GPU-Util` of your posted info is ` 0%`, but the  `Memory-Usage` is normal. I guess that there is some problem with your dataloader, maybe because of the io of your disc. You may try `watch -n 0.5 nvidia-smi` to see whether the `GPU-Util` always stays around ` 0%`.

**Comment by zhuhongyue** [comment]
@LcDog 
Thank you for your reply!
I noticed the issue about GPU-Util which remain 0% most of time.  Thus, considering your suggestion,  I check my disk state and find nothing strange. I guess the problem is related to the dataloader.
So I run your program step by step and I notice that:
```
     source_features, _ = extract_features(model, src_extfeat_loader, print_freq=args.print_freq)
     target_features, _ = extract_features(model, tgt_extfeat_loader, print_freq=args.print_freq)
     rerank_dist = re_ranking(source_features, target_features, lambda_value=args.lambda_value) 
```
these three code cost around 30 miniutes  every iteration and I suppose it means only these data preprocessing cost about 15 hours in 30 iterations. 
I am wondering how much time these code cost in your environment?
In addition, because of the limitation of gpu resources, I cannot test how much time the train part cost every iteration while another gpu program is running. Hence I will check the training time tommorow.

**Comment by lsongx** [comment]
@zhuhongyue `extract_features` is done on GPU, but `re_ranking` is written by numpy, thus the process is running on CPU. Our CPU is `Intel(R) Xeon(R) CPU E5-2620 v3 @ 2.40GHz` and `re_ranking` cost less than 5mins. Besides, `extract_features` copy CUDA variables to CPU memory, and this process also heavily depends on the hardware...

You can set `lambda_value=0` for a quiker version. Though the results maybe more unstable with this setting.

**Comment by zhuhongyue** [comment]
When I set only one gpu visible, the whole training process cost about 15 hours and the gpu utilization rate become normal as expected.
I suppose this issue is solved.
by the way, my command is 
```
CUDA_VISIBLE_DEVICES=0  python2 selftraining.py  --src_dataset dukemtmc\
	        --tgt_dataset market1501\
		--resume dukemtmc_trained.pth.tar\
		--data_dir data  \
		--logs_dir log
```
